// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts && npx tsx prisma/seed-official-products.ts && npx tsx prisma/seed-blog.ts && npx tsx prisma/seed-site-content.ts',
  },
  datasource: {
    url: process.env['DIRECT_URL'],
  },
});
